spring:
  application:
    name: ticket-form
  profiles:
      active: dev

jwt:
  expiration: 1800000  # 30분

verification:
  code-expiration-minutes: 5
  signup-window-minutes: 1
  cache-max-size: 1000